[green_agent]
agentbeats_id = "019bbde3-b2ac-72f0-a82d-98047dab178b"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bc101-348e-7730-b685-4f5c5af3eaaf"
name = "ga_suggester"
env = {GA_SUGGESTER_MODEL = "openrouter/openai/gpt-4o-mini",
    LLM_BASE_URL = "https://openrouter.ai/api/v1",
    LLM_API_KEY = "${OPENROUTER_API_KEY}",
    GA_SUGGESTER_DEBUG = "1"
    }

[config]
iterations = 3
